name: Bump version

# Run when release is published, or manually triggered
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version
        uses: alexweininger/bump-prerelease-version@main
        id: bump
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Bump version to ${{ steps.bump.outputs.new-version }} after release
          body: Automatically created by ${{ env.RUN_LINK }}
          commit-message: "Bump version to ${{ steps.bump.outputs.new-version }} after release"
          branch: "bump/v${{ steps.bump.outputs.new-version }}"
          base: main
        env:
          RUN_LINK: echo https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID