# This is a basic workflow to help you get started with Actions

name: Bump version after release

# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'Bump version (patch)'
        run: |
          npm version patch --no-git-tag-version
          echo "NEWVERSION=$(npm pkg get version) | xargs" >> $GITHUB_ENV

      - name: 'Bump version (prerelease)'
        run: |
          "npm version '${{ env.NEWVERSION }}-alpha' --no-git-tag-version"
          echo "NEWVERSION=$(npm pkg get version)" >> $GITHUB_ENV
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Bump version to ${{ env.NEWVERSION }} after release"
          body: "Pull request created automatically."
          commit-message: "Bump version to ${{ env.NEWVERSION }} after release"
          branch: "bump/v${{ env.NEWVERSION }}"
          base: main