# This is a basic workflow to help you get started with Actions

name: Bump version after release

# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name:  'Automated Version Bump'
        id: 'bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'main'
          skip-tag:  'true'
          default: prepatch
          preid: 'alpha'
          commit-message: 'Bump version to {{version}} after release'
          skip-push:  'true'

      - name: 'test'
        run: |
          echo ${{ steps.bump.outputs.newTag }}